
version: '3'
services:
  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/firefox:/config:rw"
      	restart: "unless-stopped"
    environment:
    - SECURE_CONNECTION=1 - WEB_AUTHENTICATION=1 - WEB_AUTHENTICATION_TOKEN_VALIDITY_TIME=200 - WEB_AUTHENTICATION_USERNAME=aaaaand - WEB_AUTHENTICATION_PASSWORD=bbbbbed - SECURE_CONNECTION=1 - VNC_LISTENING_PORT=-1 - WEB_AUDIO=1

